"use client";

import { useEffect, useState } from "react";
import { Activity, AlertTriangle, BarChart3, FileBarChart, TrendingDown, TrendingUp, Wallet } from "lucide-react";

type Project = { _id: string; name: string };
type Analysis = { project: { name: string; budget: number; contractAmount: number }; estimate: Record<string, number>; spent: Record<string, number>; estimatedTotal: number; actualTotal: number; variance: number; budgetRemaining: number; projectedProfit: number; boqCount: number; entryCount: number; physicalProgress: number; financialProgress: number; budgetUtilization: number; progressGap: number; progressStatus: string };
const money = (n: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 2 }).format(n);
const rows = [["Materials", "Materials", "Material"], ["Labor", "Labor", "Labor"], ["Equipment", "Equipment", "Equipment"], ["Other", "Other", "Expense"]] as const;

export default function CostAnalysisPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [data, setData] = useState<Analysis | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { fetch("/api/projects").then(r => r.json()).then(p => { setProjects(p); if (p[0]) setProjectId(p[0]._id); }); }, []);
  useEffect(() => { if (!projectId) return; setLoading(true); fetch(`/api/cost-analysis?projectId=${projectId}`).then(r => r.json()).then(setData).finally(() => setLoading(false)); }, [projectId]);

  return <main className="min-h-screen p-5 md:p-8"><div className="mx-auto max-w-7xl">
    <div className="mb-6"><div className="text-[11px] font-bold uppercase tracking-[0.14em] text-blue-600">Cost Control</div><h1 className="mt-1 text-2xl font-bold tracking-tight">Cost Analysis</h1><p className="mt-1 text-sm text-slate-500">Compare BOQ estimates, actual spending, budget utilization, and project progress.</p></div>
    <div className="card mb-5 p-4"><label className="text-[11px] font-bold uppercase tracking-wider text-slate-500">Project</label><select value={projectId} onChange={e => setProjectId(e.target.value)} className="mt-2 w-full border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 sm:max-w-xl"><option value="">Select a project</option>{projects.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select></div>
    {loading && <div className="card p-10 text-center text-sm text-slate-500">Calculating project costs...</div>}
    {data && !loading && <>
      <div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-2 xl:grid-cols-4"><Kpi label="BOQ Estimate" value={money(data.estimatedTotal)} icon={<FileBarChart size={17} />} /><Kpi label="Actual Cost" value={money(data.actualTotal)} icon={<TrendingUp size={17} />} /><Kpi label="Budget Remaining" value={money(data.budgetRemaining)} icon={<Wallet size={17} />} danger={data.budgetRemaining < 0} /><Kpi label="Projected Profit" value={money(data.projectedProfit)} icon={<TrendingDown size={17} />} danger={data.projectedProfit < 0} /></div>
      <section className="card mt-5 overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-sm font-bold">Physical vs Financial Progress</h2><p className="mt-1 text-xs text-slate-500">Financial progress is actual cost divided by contract amount.</p></div><div className="grid md:grid-cols-3"><ProgressMetric label="Physical Progress" value={data.physicalProgress} note="Latest recorded site progress" /><ProgressMetric label="Financial Progress" value={data.financialProgress} note="Actual cost / contract" /><ProgressMetric label="Budget Utilization" value={data.budgetUtilization} note="Actual cost / budget" /></div><div className={`border-t px-5 py-4 ${data.progressGap > 10 ? "border-red-200 bg-red-50" : "border-slate-200 bg-slate-50"}`}><div className="flex items-start gap-3">{data.progressGap > 10 ? <AlertTriangle size={18} className="mt-0.5 text-red-600" /> : <Activity size={18} className="mt-0.5 text-blue-600" />}<div><div className="text-sm font-bold">{data.progressStatus}</div><div className="mt-1 text-xs text-slate-500">Progress gap: <span className="font-semibold">{data.progressGap >= 0 ? "+" : ""}{data.progressGap.toFixed(1)} percentage points</span></div></div></div></div></section>
      <section className="card mt-5 overflow-x-auto"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-sm font-bold">Cost Breakdown</h2></div><table className="data-table min-w-[700px] text-sm"><thead><tr><th>Category</th><th className="text-right">Estimated</th><th className="text-right">Actual</th><th className="text-right">Variance</th><th className="text-right">Utilization</th></tr></thead><tbody>{rows.map(([label, e, a]) => { const est = data.estimate[e] || 0, act = data.spent[a] || 0, variance = est - act, pct = est ? act / est * 100 : 0; return <tr key={label}><td className="font-semibold">{label}</td><td className="text-right">{money(est)}</td><td className="text-right">{money(act)}</td><td className={`text-right font-semibold ${variance < 0 ? "text-red-600" : "text-emerald-600"}`}>{money(variance)}</td><td className="text-right">{pct.toFixed(1)}%</td></tr>; })}</tbody><tfoot><tr><td className="font-bold">TOTAL</td><td className="text-right font-bold">{money(data.estimatedTotal)}</td><td className="text-right font-bold">{money(data.actualTotal)}</td><td className={`text-right font-bold ${data.variance < 0 ? "text-red-600" : "text-emerald-600"}`}>{money(data.variance)}</td><td className="text-right font-bold">{data.estimatedTotal ? (data.actualTotal / data.estimatedTotal * 100).toFixed(1) : "0.0"}%</td></tr></tfoot></table></section>
      <div className="mt-5 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-3"><Info label="Contract Amount" value={money(data.project.contractAmount)} /><Info label="Project Budget" value={money(data.project.budget)} /><Info label="Records" value={`${data.boqCount} BOQ items · ${data.entryCount} actual costs`} /></div>
    </>}
  </div></main>;
}
function Kpi({ label, value, icon, danger = false }: { label: string; value: string; icon: React.ReactNode; danger?: boolean }) { return <div className="bg-white p-5"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider text-slate-500">{icon}{label}</div><div className={`mt-2 text-xl font-bold tracking-tight ${danger ? "text-red-600" : "text-slate-900"}`}>{value}</div></div>; }
function ProgressMetric({ label, value, note }: { label: string; value: number; note: string }) { const width = Math.min(100, Math.max(0, value)); return <div className="border-b border-slate-200 p-5 md:border-b-0 md:border-r last:md:border-r-0"><div className="text-[11px] font-bold uppercase tracking-wider text-slate-500">{label}</div><div className="mt-2 flex items-end justify-between gap-3"><span className="text-2xl font-bold">{value.toFixed(1)}%</span><BarChart3 size={18} className="mb-1 text-slate-400" /></div><div className="mt-3 h-2 bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${width}%` }} /></div><div className="mt-2 text-[11px] text-slate-500">{note}</div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><p className="text-[11px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
