"use client";

import type { FormEvent } from "react";
import { useEffect, useMemo, useState } from "react";
import { Plus, Trash2 } from "lucide-react";

export type CostCategory = "Material" | "Labor" | "Equipment" | "Expense";
type Project = { _id: string; name: string };
type Entry = { _id: string; description: string; quantity: number; unit: string; unitCost: number; amount: number; date: string; supplierOrEmployee: string; referenceNo: string; notes: string };
const money = (n: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 2 }).format(n);

export default function CostLedger({ category, title, description }: { category: CostCategory; title: string; description: string }) {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [entries, setEntries] = useState<Entry[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ description: "", quantity: "1", unit: category === "Material" ? "pcs" : category === "Labor" ? "day" : category === "Equipment" ? "day" : "lot", unitCost: "0", amount: "0", date: new Date().toISOString().slice(0, 10), supplierOrEmployee: "", referenceNo: "", notes: "" });

  useEffect(() => { fetch("/api/projects").then(r => r.json()).then(data => { setProjects(Array.isArray(data) ? data : []); if (data[0]) setProjectId(data[0]._id); }).catch(() => setError("Could not load projects.")); }, []);
  useEffect(() => { if (!projectId) return; setLoading(true); fetch(`/api/costs?projectId=${projectId}&category=${category}`).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(data => setEntries(Array.isArray(data) ? data : [])).catch(() => setError("Could not load cost records.")).finally(() => setLoading(false)); }, [projectId, category]);
  const total = useMemo(() => entries.reduce((sum, e) => sum + e.amount, 0), [entries]);
  const calculated = (Number(form.quantity) || 0) * (Number(form.unitCost) || 0);

  async function addEntry(e: FormEvent) { e.preventDefault(); if (!projectId) return; setError(""); const response = await fetch("/api/costs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, projectId, category, amount: category === "Expense" ? Number(form.amount) : calculated }) }); if (!response.ok) { setError("Could not save this record."); return; } const item = await response.json(); setEntries(prev => [item, ...prev]); setOpen(false); setForm({ ...form, description: "", quantity: "1", unitCost: "0", amount: "0", referenceNo: "", notes: "" }); }
  async function removeEntry(id: string) { if (!window.confirm("Delete this record?")) return; const response = await fetch(`/api/costs/${id}`, { method: "DELETE" }); if (response.ok) setEntries(prev => prev.filter(e => e._id !== id)); else setError("Could not delete this record."); }

  return <main className="min-h-screen p-5 md:p-8"><div className="mx-auto max-w-[1500px]">
    <div className="mb-6 flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-600">Cost Control / Register</div><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div><button disabled={!projectId} onClick={() => setOpen(true)} className="flex items-center justify-center gap-2 bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-40"><Plus size={16}/> Record {category === "Expense" ? "Expense" : category}</button></div>
    {error && <div className="mb-5 border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</div>}
    <div className="mb-5 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-[1fr_240px_240px]"><div className="bg-white p-4"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Project</label><select value={projectId} onChange={e => setProjectId(e.target.value)} className="mt-1.5 w-full border-0 bg-white p-0 text-sm font-bold outline-none"><option value="">Select a project</option>{projects.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select></div><div className="bg-white p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Recorded Entries</div><div className="mt-1 text-lg font-bold tabular-nums">{entries.length}</div></div><div className="bg-white p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Total Actual Cost</div><div className="mt-1 text-lg font-bold tabular-nums">{money(total)}</div></div></div>
    <div className="overflow-x-auto border border-slate-200 bg-white">{loading ? <div className="p-12 text-center text-sm text-slate-500">Loading register...</div> : <table className="data-table min-w-[1000px] text-sm"><thead><tr><th>Date</th><th>Description</th><th>Supplier / Employee</th><th>Reference</th><th className="text-right">Qty</th><th>Unit</th><th className="text-right">Unit Cost</th><th className="text-right">Actual Amount</th><th></th></tr></thead><tbody>{entries.map(e => <tr key={e._id}><td className="whitespace-nowrap">{new Date(e.date).toLocaleDateString("en-PH")}</td><td className="font-semibold text-slate-900">{e.description}</td><td>{e.supplierOrEmployee || "—"}</td><td>{e.referenceNo || "—"}</td><td className="text-right tabular-nums">{e.quantity}</td><td>{e.unit}</td><td className="text-right tabular-nums">{money(e.unitCost)}</td><td className="text-right font-bold tabular-nums">{money(e.amount)}</td><td><button aria-label="Delete record" onClick={() => removeEntry(e._id)} className="p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></td></tr>)}</tbody>{entries.length > 0 && <tfoot><tr><td colSpan={7} className="text-right font-bold">REGISTER TOTAL</td><td className="text-right text-base font-bold">{money(total)}</td><td/></tr></tfoot>}</table>}{!loading && entries.length === 0 && <div className="p-12 text-center text-sm text-slate-500">No {title.toLowerCase()} records for this project.</div>}</div>
    {open && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={addEntry} className="w-full max-w-2xl border border-slate-200 bg-white shadow-2xl"><div className="border-b border-slate-200 px-6 py-5"><div className="text-[10px] font-bold uppercase tracking-wider text-blue-600">New Cost Record</div><h2 className="mt-1 text-xl font-bold">Record {category === "Expense" ? "Expense" : category}</h2></div><div className="grid gap-4 p-6 sm:grid-cols-2"><Field label="Description" required value={form.description} onChange={v=>setForm({...form,description:v})}/><Field label="Date" required type="date" value={form.date} onChange={v=>setForm({...form,date:v})}/><Field label={category === "Labor" ? "Employee" : category === "Material" ? "Supplier" : "Supplier / Provider"} value={form.supplierOrEmployee} onChange={v=>setForm({...form,supplierOrEmployee:v})}/><Field label="Reference No." value={form.referenceNo} onChange={v=>setForm({...form,referenceNo:v})}/>{category !== "Expense" ? <><Field label="Quantity" required type="number" min="0" step="any" value={form.quantity} onChange={v=>setForm({...form,quantity:v})}/><Field label="Unit" required value={form.unit} onChange={v=>setForm({...form,unit:v})}/><Field label="Unit Cost" required type="number" min="0" step="any" value={form.unitCost} onChange={v=>setForm({...form,unitCost:v})}/></> : <Field label="Amount" required type="number" min="0" step="any" value={form.amount} onChange={v=>setForm({...form,amount:v})}/>}<label className="sm:col-span-2"><span className="text-sm font-semibold">Notes</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={3} className="mt-1.5 w-full border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/></label></div>{category !== "Expense" && <div className="mx-6 mb-2 border border-slate-200 bg-slate-50 px-4 py-3 text-right text-sm"><span className="text-slate-500">Calculated actual cost </span><b>{money(calculated)}</b></div>}<div className="flex justify-end gap-3 border-t border-slate-200 bg-slate-50 px-6 py-4"><button type="button" onClick={()=>setOpen(false)} className="border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Cancel</button><button className="bg-blue-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Save Record</button></div></form></div>}
  </div></main>;
}
function Field({label,value,onChange,type="text",required=false,min,step}:{label:string,value:string,onChange:(v:string)=>void,type?:string,required?:boolean,min?:string,step?:string}){return <label><span className="text-sm font-semibold text-slate-700">{label}{required&&" *"}</span><input required={required} min={min} step={step} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/></label>}
