"use client";

import { useEffect, useMemo, useState } from "react";
import { Printer, RefreshCw, AlertTriangle } from "lucide-react";

type Project={_id:string;name:string;client?:string;location?:string;budget:number;contractAmount:number;status:string;projectManager?:string};
type Analysis={project:Project;estimate:Record<string,number>;spent:Record<string,number>;estimatedTotal:number;actualTotal:number;variance:number;budgetRemaining:number;projectedProfit:number;boqCount:number;entryCount:number;physicalProgress:number;financialProgress:number;budgetUtilization:number;progressGap:number;progressStatus:string};
const money=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:2}).format(Number(n)||0);
const categories=[["Materials","Material"],["Labor","Labor"],["Equipment","Equipment"],["Other","Expense"]] as const;

export default function ReportsPage(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[data,setData]=useState<Analysis|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async(id=projectId)=>{if(!id)return;setLoading(true);setError("");try{const r=await fetch(`/api/cost-analysis?projectId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not prepare report.");setData(d)}catch(e){setError(e instanceof Error?e.message:"Could not prepare report.")}finally{setLoading(false)}};
 useEffect(()=>{fetch("/api/projects",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(p=>{const list=Array.isArray(p)?p:[];setProjects(list);if(list[0])setProjectId(list[0]._id)}).catch(()=>setError("Could not load projects."))},[]);
 useEffect(()=>{load()},[projectId]);
 const variancePct=useMemo(()=>data?.estimatedTotal?data.variance/data.estimatedTotal*100:0,[data]);
 return <main className="min-h-screen p-5 md:p-8"><div className="mx-auto max-w-6xl">
  <header className="mb-6 flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between print:hidden"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-600">Documentation / Reporting</div><h1 className="mt-1 text-2xl font-bold tracking-tight">Project Reports</h1><p className="mt-1 text-sm text-slate-500">Formal cost, budget and progress report for project review.</p></div><div className="flex gap-2"><button onClick={()=>load()} disabled={!projectId||loading} className="flex items-center gap-2 border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-40"><RefreshCw size={16} className={loading?"animate-spin":""}/> Refresh</button><button disabled={!data} onClick={()=>window.print()} className="flex items-center gap-2 bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40"><Printer size={16}/> Print Report</button></div></header>
  {error&&<div className="mb-5 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 print:hidden">{error}</div>}
  <div className="mb-6 border border-slate-200 bg-white p-4 print:hidden"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Project</label><select value={projectId} onChange={e=>setProjectId(e.target.value)} className="mt-1.5 w-full border border-slate-300 px-3 py-2.5 text-sm font-semibold sm:max-w-xl"><option value="">Select a project</option>{projects.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></div>
  {loading?<div className="border border-slate-200 bg-white p-12 text-center text-sm text-slate-500 print:hidden"><RefreshCw className="mx-auto mb-3 animate-spin" size={20}/>Preparing report...</div>:data&&<section className="border border-slate-200 bg-white p-6 md:p-10 print:border-0 print:p-0">
   <header className="border-b-2 border-slate-900 pb-6"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Construction Cost & Project Management System</div><div className="mt-3 flex flex-col justify-between gap-4 sm:flex-row"><div><h2 className="text-3xl font-bold tracking-tight">Project Cost Report</h2><p className="mt-1 text-sm text-slate-500">Cost, budget and progress control summary</p></div><div className="text-left text-xs sm:text-right"><div className="font-bold uppercase text-slate-500">Status</div><div className="mt-1 font-bold">{data.project.status}</div></div></div><div className="mt-6 grid gap-x-8 gap-y-3 text-sm sm:grid-cols-2"><Info label="Project" value={data.project.name}/><Info label="Client" value={data.project.client||"—"}/><Info label="Location" value={data.project.location||"—"}/><Info label="Project Engineer" value={data.project.projectManager||"—"}/><Info label="Contract Amount" value={money(data.project.contractAmount)}/><Info label="Project Budget" value={money(data.project.budget)}/></div></header>
   <div className="mt-7 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4"><Summary label="BOQ Estimate" value={money(data.estimatedTotal)}/><Summary label="Actual Cost" value={money(data.actualTotal)}/><Summary label="Variance" value={money(data.variance)} danger={data.variance<0}/><Summary label="Projected Profit" value={money(data.projectedProfit)} danger={data.projectedProfit<0}/></div>
   <h3 className="mt-8 text-base font-bold uppercase tracking-wider">Cost Summary by Category</h3><table className="data-table mt-3 text-sm"><thead><tr><th>Category</th><th className="text-right">Estimated</th><th className="text-right">Actual</th><th className="text-right">Variance</th></tr></thead><tbody>{categories.map(([label,key])=>{const e=Number(data.estimate[label]||0),a=Number(data.spent[key]||0),v=e-a;return <tr key={label}><td className="font-semibold">{label}</td><td className="text-right">{money(e)}</td><td className="text-right">{money(a)}</td><td className={`text-right font-bold ${v<0?"text-red-600":"text-emerald-700"}`}>{money(v)}</td></tr>})}</tbody></table>
   <h3 className="mt-8 text-base font-bold uppercase tracking-wider">Progress Control</h3><div className="mt-3 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-3"><Summary label="Physical Progress" value={`${Number(data.physicalProgress||0).toFixed(1)}%`}/><Summary label="Financial Progress" value={`${Number(data.financialProgress||0).toFixed(1)}%`}/><Summary label="Budget Utilization" value={`${Number(data.budgetUtilization||0).toFixed(1)}%`}/></div>
   <div className={`mt-4 flex items-start gap-3 border p-4 text-sm ${data.progressGap>10||data.budgetRemaining<0?"border-red-200 bg-red-50 text-red-800":"border-slate-200 bg-slate-50 text-slate-700"}`}>{data.progressGap>10||data.budgetRemaining<0?<AlertTriangle size={18} className="mt-0.5 shrink-0"/>:null}<div><b>{data.progressStatus}</b><div className="mt-1">Progress gap: {data.progressGap>=0?"+":""}{Number(data.progressGap||0).toFixed(1)} points · Cost variance: {variancePct>=0?"+":""}{variancePct.toFixed(1)}% of BOQ estimate.</div></div></div>
   <div className="mt-8 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2"><Summary label="Budget Remaining" value={money(data.budgetRemaining)} danger={data.budgetRemaining<0}/><Summary label="Cost Utilization vs BOQ" value={`${data.estimatedTotal?(data.actualTotal/data.estimatedTotal*100).toFixed(1):"0.0"}%`}/></div>
   <footer className="mt-10 border-t border-slate-200 pt-5 text-xs text-slate-500">This report contains {data.boqCount} BOQ item(s) and {data.entryCount} actual cost record(s). Generated from current project records.</footer>
  </section>}
  {!loading&&!data&&!error&&<div className="border border-slate-200 bg-white p-12 text-center text-sm text-slate-500">Select a project to generate the report.</div>}
 </div></main>
}
function Info({label,value}:{label:string;value:string}){return <div><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</div><div className="mt-1 font-semibold text-slate-900">{value}</div></div>}
function Summary({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className="bg-white p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</div><div className={`mt-1 text-lg font-bold tabular-nums ${danger?"text-red-600":"text-slate-900"}`}>{value}</div></div>}
