"use client";

import { FormEvent, useEffect, useState } from "react";
import { Plus, Receipt, Users, Truck } from "lucide-react";

type Project={_id:string;name:string};
type Entry={_id:string;date:string;description?:string;employeeName?:string;role?:string;hours?:number;hourlyRate?:number;equipmentName?:string;ratePerHour?:number;category?:string;amount?:number;operator?:string};
const money=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(n);

export default function CostsPage(){
 const [projects,setProjects]=useState<Project[]>([]); const [projectId,setProjectId]=useState(""); const [tab,setTab]=useState<"labor"|"equipment"|"expenses">("labor"); const [rows,setRows]=useState<Entry[]>([]); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>({});
 useEffect(()=>{fetch("/api/projects").then(r=>r.json()).then(d=>{setProjects(d);if(d[0])setProjectId(d[0]._id)})},[]);
 useEffect(()=>{if(projectId){fetch(`/api/${tab}?projectId=${projectId}`).then(r=>r.json()).then(setRows)}},[projectId,tab]);
 const total=rows.reduce((s,r)=>s+(tab==="labor"?(r.hours||0)*(r.hourlyRate||0):tab==="equipment"?(r.hours||0)*(r.ratePerHour||0):(r.amount||0)),0);
 function defaults(){return tab==="labor"?{date:new Date().toISOString().slice(0,10),employeeName:"",role:"Worker",hours:"8",hourlyRate:"0"}:tab==="equipment"?{date:new Date().toISOString().slice(0,10),equipmentName:"",hours:"1",ratePerHour:"0",operator:""}:{date:new Date().toISOString().slice(0,10),category:"Other",description:"",amount:"0",reference:""}}
 async function submit(e:FormEvent){e.preventDefault();const r=await fetch(`/api/${tab}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,projectId})});if(r.ok){setRows([await r.json(),...rows]);setOpen(false)}}
 return <main className="min-h-screen bg-gray-50 p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold">Project Costs</h1><p className="mt-1 text-sm text-gray-500">Track actual labor, equipment usage, and project expenses.</p></div><button onClick={()=>{setForm(defaults());setOpen(true)}} disabled={!projectId} className="flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Plus size={17}/> Add Entry</button></div>
 <div className="mb-5 rounded-xl border border-gray-200 bg-white p-4"><label className="text-sm font-semibold">Project</label><select value={projectId} onChange={e=>setProjectId(e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2.5 text-sm sm:max-w-xl"><option value="">Select a project</option>{projects.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></div>
 <div className="grid gap-4 sm:grid-cols-3"><button onClick={()=>setTab("labor")} className={`rounded-xl border bg-white p-5 text-left ${tab==="labor"?"ring-2 ring-slate-800":""}`}><Users className="text-gray-500"/><div className="mt-3 text-sm text-gray-500">Labor Cost</div><div className="text-xl font-bold">{tab==="labor"?money(total):"View labor"}</div></button><button onClick={()=>setTab("equipment")} className={`rounded-xl border bg-white p-5 text-left ${tab==="equipment"?"ring-2 ring-slate-800":""}`}><Truck className="text-gray-500"/><div className="mt-3 text-sm text-gray-500">Equipment Cost</div><div className="text-xl font-bold">{tab==="equipment"?money(total):"View equipment"}</div></button><button onClick={()=>setTab("expenses")} className={`rounded-xl border bg-white p-5 text-left ${tab==="expenses"?"ring-2 ring-slate-800":""}`}><Receipt className="text-gray-500"/><div className="mt-3 text-sm text-gray-500">Other Expenses</div><div className="text-xl font-bold">{tab==="expenses"?money(total):"View expenses"}</div></button></div>
 <div className="mt-5 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Details</th><th className="px-4 py-3 text-right">Cost</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r._id}><td className="px-4 py-3">{new Date(r.date).toLocaleDateString()}</td><td className="px-4 py-3 font-medium">{r.description||r.employeeName||r.equipmentName}</td><td className="px-4 py-3 text-gray-500">{tab==="labor"?`${r.role} • ${r.hours} hrs @ ${money(r.hourlyRate||0)}`:tab==="equipment"?`${r.hours} hrs @ ${money(r.ratePerHour||0)}`:r.category}</td><td className="px-4 py-3 text-right font-semibold">{money(tab==="labor"?(r.hours||0)*(r.hourlyRate||0):tab==="equipment"?(r.hours||0)*(r.ratePerHour||0):(r.amount||0))}</td></tr>)}</tbody></table>{rows.length===0&&<div className="p-12 text-center text-sm text-gray-500">No {tab} entries for this project.</div>}</div>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Add {tab==="labor"?"Labor":tab==="equipment"?"Equipment Usage":"Expense"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(form).map(([k,v]:any)=><label key={k}><span className="text-sm font-medium capitalize">{k.replace(/([A-Z])/g," $1")}</span><input required type={k==="date"?"date":(["hours","hourlyRate","ratePerHour","amount"].includes(k)?"number":"text")} value={v} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm"/></label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Cancel</button><button className="rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Save Entry</button></div></form></div>}
 </div></main>;
}
